# =========================
# ConfigMap
# =========================
apiVersion: v1
kind: ConfigMap
metadata:
  name: springappconfigmap
data:
  username: springapp
  database: userdb

---
# =========================
# Secret
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: springappsecrets
type: Opaque
stringData:
  password: devdb@123

---
# =========================
# PersistentVolumeClaim (EKS SAFE)
# =========================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# =========================
# PersistentVolume
# =========================

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongo
    
---
# =========================
# Spring Boot Deployment
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springappcontainer
        image: pvreddy1/mongospring:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: springappconfigmap
              key: username
        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springappsecrets
              key: password
        - name: MONGO_DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: springappconfigmap
              key: database
        - name: MONGO_DB_HOSTNAME
          value: mongo

---
# =========================
# Spring Boot Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: springapp
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080

---
# =========================
# MongoDB ReplicaSet
# =========================
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodbcontainer
        image: mongo:8.0.9-noble
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: springappconfigmap
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springappsecrets
              key: password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: springappconfigmap
              key: database
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc

---
# =========================
# MongoDB Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
